name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3

      - name: Deploy Flutter web app to github pages
        uses: erickzanardo/flutter-gh-pages@v3
        with:
          webRenderer: canvaskit
